name: Docker Image CI/CD

on:
  push:
    branches:
      - main  # Déclenche le pipeline à chaque push sur la branche principale

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Connexion à Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construction de l'image Docker
        run: |
          docker build -t mouhamadoukane/examendevops:latest .

      - name: Pousser l'image vers Docker Hub
        run: |
          docker push mouhamadoukane/examendevops:latest




name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build -t votre_nom_utilisateur_dockerhub/simple-http-server:latest .

    - name: Push Docker image
      run: |
        docker tag simple-http-server votre_nom_utilisateur_dockerhub/simple-http-server:latest
        docker push votre_nom_utilisateur_dockerhub/simple-http-server:latest